// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create() {
  return window['go']['service']['ClusterService']['Create']();
}

export function Delete() {
  return window['go']['service']['ClusterService']['Delete']();
}

export function GetPrerequisites() {
  return window['go']['service']['ClusterService']['GetPrerequisites']();
}

export function GetStatus() {
  return window['go']['service']['ClusterService']['GetStatus']();
}
