// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cluster} from '../models';
import {service} from '../models';

export function Create():Promise<void>;

export function Delete():Promise<void>;

export function GetPrerequisites():Promise<cluster.Prerequisites>;

export function GetStatus():Promise<service.ClusterStatusResponse>;
