// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocsProxyURL():Promise<string>;

export function Start():Promise<number>;

export function Stop():Promise<void>;
