// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocsProxyURL() {
  return window['go']['service']['DocsService']['GetDocsProxyURL']();
}

export function Start() {
  return window['go']['service']['DocsService']['Start']();
}

export function Stop() {
  return window['go']['service']['DocsService']['Stop']();
}
