// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishExam() {
  return window['go']['service']['ExamService']['FinishExam']();
}

export function GetStatus() {
  return window['go']['service']['ExamService']['GetStatus']();
}

export function ListExams() {
  return window['go']['service']['ExamService']['ListExams']();
}

export function SelectExam(arg1) {
  return window['go']['service']['ExamService']['SelectExam'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['ExamService']['SetContext'](arg1);
}

export function StartExam(arg1) {
  return window['go']['service']['ExamService']['StartExam'](arg1);
}
