// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {exam} from '../models';
import {question} from '../models';
import {context} from '../models';

export function FinishExam():Promise<service.ExamResultResponse>;

export function GetStatus():Promise<exam.StatusResponse>;

export function ListExams():Promise<Array<question.ExamSummary>>;

export function SelectExam(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartExam(arg1:number):Promise<void>;
