// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAttempt(arg1) {
  return window['go']['service']['HistoryService']['DeleteAttempt'](arg1);
}

export function GetAttempt(arg1) {
  return window['go']['service']['HistoryService']['GetAttempt'](arg1);
}

export function ListAttempts() {
  return window['go']['service']['HistoryService']['ListAttempts']();
}

export function SaveAttempt(arg1) {
  return window['go']['service']['HistoryService']['SaveAttempt'](arg1);
}
