// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function DeleteAttempt(arg1:string):Promise<void>;

export function GetAttempt(arg1:string):Promise<service.AttemptRecord>;

export function ListAttempts():Promise<Array<service.AttemptSummary>>;

export function SaveAttempt(arg1:service.AttemptRecord):Promise<void>;
