// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {question} from '../models';
import {service} from '../models';

export function GetDeckTopic(arg1:string):Promise<question.DeckTopic>;

export function GetQuestion(arg1:string):Promise<service.QuestionDetailResponse>;

export function ListDeckTopics():Promise<Array<question.DeckTopicSummary>>;

export function ListExams():Promise<Array<question.ExamSummary>>;

export function ListQuestions():Promise<Array<question.QuestionSummary>>;
