// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeckTopic(arg1) {
  return window['go']['service']['QuestionService']['GetDeckTopic'](arg1);
}

export function GetQuestion(arg1) {
  return window['go']['service']['QuestionService']['GetQuestion'](arg1);
}

export function ListDeckTopics() {
  return window['go']['service']['QuestionService']['ListDeckTopics']();
}

export function ListExams() {
  return window['go']['service']['QuestionService']['ListExams']();
}

export function ListQuestions() {
  return window['go']['service']['QuestionService']['ListQuestions']();
}
