// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetTerminalURL():Promise<string>;

export function Port():Promise<number>;

export function Restart():Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Start():Promise<number>;

export function Stop():Promise<void>;
