// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTerminalURL() {
  return window['go']['service']['TerminalService']['GetTerminalURL']();
}

export function Port() {
  return window['go']['service']['TerminalService']['Port']();
}

export function Restart() {
  return window['go']['service']['TerminalService']['Restart']();
}

export function SetContext(arg1) {
  return window['go']['service']['TerminalService']['SetContext'](arg1);
}

export function Start() {
  return window['go']['service']['TerminalService']['Start']();
}

export function Stop() {
  return window['go']['service']['TerminalService']['Stop']();
}
