// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ValidateQuestion(arg1) {
  return window['go']['service']['ValidatorService']['ValidateQuestion'](arg1);
}
