// Wails bindings — auto-generated by `wails dev` / `wails build`.
// These modules map directly to the Go service methods.

import { ListExams, ListQuestions, GetQuestion } from '../../wailsjs/go/service/QuestionService';
import { SelectExam, StartExam, GetStatus, FinishExam } from '../../wailsjs/go/service/ExamService';
import { ValidateQuestion } from '../../wailsjs/go/service/ValidatorService';
import { GetPrerequisites, GetStatus as GetClusterStatus } from '../../wailsjs/go/service/ClusterService';
import { GetTerminalURL } from '../../wailsjs/go/service/TerminalService';
import { GetDocsProxyURL } from '../../wailsjs/go/service/DocsService';
import { EnterFullscreen, ExitFullscreen } from '../../wailsjs/go/main/App';

import { ListAttempts, GetAttempt, DeleteAttempt } from '../../wailsjs/go/service/HistoryService';
import type {
  ExamSummary,
  QuestionSummary,
  QuestionDetail,
  ExamStatus,
  ExamResult,
  ValidationResponse,
  Prerequisites,
  ClusterStatus,
  AttemptSummary,
  AttemptRecord,
} from '../types';

// Wails generates class-based types; our components use interfaces.
// The runtime shapes are identical, so we cast at the boundary.
export const api = {
  getExams: async (): Promise<ExamSummary[]> => {
    return ListExams() as any;
  },

  selectExam: async (examId: string): Promise<void> => {
    await SelectExam(examId);
  },

  getQuestions: async (): Promise<QuestionSummary[]> => {
    return ListQuestions() as any;
  },

  getQuestion: async (id: string): Promise<QuestionDetail> => {
    return GetQuestion(id) as any;
  },

  startExam: async (duration: number): Promise<{ status: string }> => {
    await StartExam(duration);
    return { status: 'started' };
  },

  getExamStatus: async (): Promise<ExamStatus> => {
    return GetStatus() as any;
  },

  finishExam: async (): Promise<ExamResult> => {
    return FinishExam() as any;
  },

  validate: async (id: string): Promise<ValidationResponse> => {
    return ValidateQuestion(id) as any;
  },

  getPrerequisites: async (): Promise<Prerequisites> => {
    return GetPrerequisites() as any;
  },

  getClusterStatus: async (): Promise<ClusterStatus> => {
    return GetClusterStatus() as any;
  },

  createCluster: async (): Promise<{ status: string }> => {
    return { status: 'use startExam instead' };
  },

  deleteCluster: async (): Promise<{ status: string }> => {
    return { status: 'not implemented in desktop mode' };
  },

  // History
  listAttempts: async (): Promise<AttemptSummary[]> => {
    const result = await ListAttempts();
    return (result || []) as any;
  },

  getAttempt: async (id: string): Promise<AttemptRecord> => {
    return GetAttempt(id) as any;
  },

  deleteAttempt: async (id: string): Promise<void> => {
    await DeleteAttempt(id);
  },
};

export { GetTerminalURL, GetDocsProxyURL, EnterFullscreen, ExitFullscreen };
