// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterFullscreen() {
  return window['go']['main']['App']['EnterFullscreen']();
}

export function ExitFullscreen() {
  return window['go']['main']['App']['ExitFullscreen']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}
