// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterFullscreen():Promise<void>;

export function ExitFullscreen():Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;
